# Generated by Django 3.2 on 2022-11-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('genre_ids', models.JSONField()),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.TextField()),
                ('original_language', models.TextField()),
                ('popularity', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('release_date', models.DateField()),
                ('vote_average', models.FloatField()),
            ],
        ),
    ]
