# Generated by Django 3.2 on 2022-11-16 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
