# Generated by Django 3.2 on 2022-11-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_remove_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
