# Generated by Django 3.2 on 2022-11-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.JSONField(default=False),
        ),
    ]
