# Generated by Django 3.2 on 2022-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_movie_genre_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
