# Generated by Django 3.2 on 2022-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_alter_movie_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedMovie',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_ids', models.JSONField()),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.TextField()),
                ('actors', models.JSONField(default=False)),
            ],
        ),
    ]
