# Generated by Django 3.2 on 2022-11-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_article_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
