# Generated by Django 3.2 on 2022-11-22 15:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile'),
        ),
    ]
